backend = "glx";              # pakai GLX biar aman di AMD
vsync = false;                 # cegah tearing
unredir-if-possible = false;  # cegah layar jadi hitam
use-damage = false;            # performa lebih bagus di AMD

#################################
# Visual
#################################
shadow = false;      # matiin shadow biar ringan
fading = false;      # matiin fading animasi
blur-method = "none"; # gak usah blur, hemat resource

#################################
# Optional: transparansi khusus kitty
#################################
# opacity-rule = [ "90:class_g = 'kitty'" ];
