backend = "xrender";              
vsync = true;                 
use-damage = true;            
unredir-if-possible = true;  

refresh-rate = 0;
detect-rounded-corners = true;
detect-client-opacity = true;

shadow = false;
fading = false;
blur-method = "none";

inactive-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;

opacity-rule = [
  "90:class_g = 'i3bar'"
];

glx-no-stencil = true;
glx-no-rebind-pixmap = true;

